name: Frontend CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: |
          cd wasteless
          npm install

      - name: Run Tests
        run: |
          cd wasteless
          npm test

      - name: Build Wasteless Web Application
        run: |
          cd wasteless
          npm run build

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: nusissteam21/wasteless-frontend
          tags: latest
          registry: docker.io
          dockerfile: wasteless/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
